---
title: "GroupProject1"
output: 
  pdf_document: 
    fig_height: 5.5
    fig_width: 7
    highlight: kate
    latex_engine: xelatex
---

Q2

```{r}
library("lpSolve")
maturityYear = c(1,2,2,3,4,5,5,6,7,8)
# Price of each bond
c = c(102,99,101,98,98,104,100,101,102,94)
# Coupon rate 
coupon = c(5,3.5,5,3.5,4,9,6,8,9,7)
# Liability schedule
b = c(12000,18000,20000,20000,16000,15000,12000,10000)
dir = rep("=",8)

# Matrix of cash flow from coupon
couponTol = matrix(0,8,10)
for(i in 1:10){
  couponTol[1:maturityYear[i], i] = 1
}
couponTol = couponTol %*% diag(coupon)

# Matrix of cash flow from principle at maturity
maturityTol = matrix(0,8,10)
for(i in 1:10){
  maturityTol[maturityYear[i],i] = 100
}

# Total cash inflows
A = couponTol + maturityTol

s = lp("min",c,A,dir,b)
s$solution
```

Q3

```{r}
dedication <- function(P,C,M,L){
  
  t = length(L)
  n = length(M)
  
  couponTol = matrix(0,t,n)
  for(i in 1:n){
    couponTol[1:M[i],i] = 1
  }
  couponTol = couponTol %*% diag(C)
  
  maturityTol = matrix(0,t,n)
  for(i in 1:n){
    maturityTol[j = M[i],i] = 100
  }
  
  dir = rep(">=",t)
  s = lp("min",P,couponTol + maturityTol,dir,L)
  if (s$status ==0){
    return(s$solution)
  }
  # Catch Exceptions
  else(
    print("No feasible solution found")
  )
}

# Test the function with Q2
dedication(c,coupon,maturityYear,b)

# Test with exception case
maturityYear = rep(1,10)
coupon = rep(0,10)
dedication(c,coupon,maturityYear,b)
```

Q4

```{r}
library(rvest)
library(XML)
url = "http://online.wsj.com/mdc/public/page/2_3020-treasury.html"
table = readHTMLTable(url, header=T, which=3,stringsAsFactors=F)
table$Date <- as.Date(table$Maturity, format="%m/%d/%Y")
table$year  = format(table$Date,"%Y")
table$monthday  = format(table$Date,"%m%d")
attach(table)
sub = subset(table,year > 2016)
sub = subset(sub, monthday == '1231' | monthday == '0630',select=c(Coupon,year,monthday,Asked))
rownames(sub) <- 1:nrow(sub)
detach(table)
sub

num = c(3,3,3,2,2,2,2,2,2,1,1)
maturityYear = c(1,1,1,2,2,2,3,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,11,12)
coupon = rep(0,24)
for (i in 1:24){
  coupon[i] <- as.numeric(sub$Coupon[i])
}

c = rep(0,24)
for (i in 1:24){
  c[i] <- as.numeric(sub$Asked[i])
}

# Liability schedule
b = 1000000*c(9,9,10,10,6,6,9,9,10,10,5,3)
dir = rep("=",12)

dedication(c,coupon,maturityYear,b)

```

